import '@/styles/globals.css'
import Head from 'next/head'
import ScrollToTopButton from '@/components/layout/scroll-to-top'

export default function App({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>madel.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/m.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
      </Head>
      <Component {...pageProps} />
      <ScrollToTopButton/>
    </div>
  )
}
